import { appTools, defineConfig } from '@modern-js/app-tools';
import { ModuleFederationPlugin } from '@module-federation/enhanced/rspack';

// https://modernjs.dev/en/configure/app/usage
export default defineConfig({
  runtime: {
    router: true,
  },
  dev: {
    port: 3001,
    assetPrefix: 'http://localhost:3001/',
  },
  server: {
    ssr: false,
  },
  source: {
    // automatically generated asynchronous boundary via Dynamic Import, allowing the page code to consume remote modules generated by the module federation.
    enableAsyncEntry: true,
  },
  tools: {
    rspack: (config, { appendPlugins }) => {
      appendPlugins([
        new ModuleFederationPlugin({
          name: 'home',
          remotes: {
            login: 'login@http://localhost:3002/mf-manifest.json',
          },
          shared: {
            react: {
              singleton: true,
              requiredVersion: '18',
            },
            'react-dom': {
              singleton: true,
              requiredVersion: '18',
            },
          },
        }),
      ]);
    },
  },
  plugins: [
    appTools({
      bundler: 'experimental-rspack',
    }),
  ],
});
